name: gg_midi_vars
description: This packages defines the MIDI variables particularly for MIDI note names and control change names.
version: 1.0.4
repository: https://github.com/inlavigo/gg_midi_vars

environment:
  sdk: ^3.2.0

dev_dependencies:
  args: ^2.4.2
  coverage: ^1.7.2
  gg_capture_print: ^1.0.2
  lints: ^3.0.0
  test: ^1.24.0
  yaml: ^3.1.2